import type { Patient, Appointment, SOAPNote, Invoice, InvoiceItem, StaffProfile, RecentActivity } from './types'

export const mockStaff: StaffProfile[] = [
  {
    id: 'staff-1',
    user_id: 'user-1',
    full_name: 'Dr. Swechchha Rajput',
    email: 'swechchha.rajput@rehabme.com',
    role: 'admin',
    phone: '+1 (555) 001-0001',
    specialty: 'Physiotherapy',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'staff-2',
    user_id: 'user-2',
    full_name: 'Dr. James Okafor',
    email: 'james.okafor@rehabme.com',
    role: 'therapist',
    phone: '+1 (555) 001-0002',
    specialty: 'Occupational Therapy',
    is_active: true,
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'staff-3',
    user_id: 'user-3',
    full_name: 'Ms. Priya Sharma',
    email: 'priya.sharma@rehabme.com',
    role: 'therapist',
    phone: '+1 (555) 001-0003',
    specialty: 'Speech Therapy',
    is_active: true,
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2024-02-01T00:00:00Z',
  },
  {
    id: 'staff-4',
    user_id: 'user-4',
    full_name: 'Mr. Carlos Rivera',
    email: 'carlos.rivera@rehabme.com',
    role: 'therapist',
    phone: '+1 (555) 001-0004',
    specialty: 'Sports Rehabilitation',
    is_active: true,
    created_at: '2024-02-15T00:00:00Z',
    updated_at: '2024-02-15T00:00:00Z',
  },
]

export const mockPatients: Patient[] = [
  {
    id: 'pat-1',
    mrn: 'MRN-2024-001',
    full_name: 'Emily Johnson',
    date_of_birth: '1985-03-15',
    gender: 'female',
    phone: '+1 (555) 234-5678',
    email: 'emily.johnson@email.com',
    address: '123 Maple Street',
    city: 'Springfield',
    state: 'IL',
    zip: '62701',
    emergency_contact_name: 'Robert Johnson',
    emergency_contact_phone: '+1 (555) 234-5679',
    insurance_provider: 'BlueCross BlueShield',
    insurance_policy_number: 'BCB-123456789',
    insurance_group_number: 'GRP-001',
    referring_physician: 'Dr. Alan Thompson',
    primary_diagnosis: 'Lumbar Disc Herniation',
    medical_history: 'Previous L4-L5 disc herniation (2020). No surgical history.',
    allergies: 'Penicillin',
    medications: 'Ibuprofen 400mg PRN',
    is_active: true,
    created_at: '2024-01-10T09:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
  },
  {
    id: 'pat-2',
    mrn: 'MRN-2024-002',
    full_name: 'Michael Chen',
    date_of_birth: '1978-07-22',
    gender: 'male',
    phone: '+1 (555) 345-6789',
    email: 'michael.chen@email.com',
    address: '456 Oak Avenue',
    city: 'Springfield',
    state: 'IL',
    zip: '62702',
    emergency_contact_name: 'Lisa Chen',
    emergency_contact_phone: '+1 (555) 345-6790',
    insurance_provider: 'Aetna',
    insurance_policy_number: 'AET-987654321',
    primary_diagnosis: 'Rotator Cuff Tear (Post-Op)',
    medical_history: 'Right rotator cuff repair surgery March 2024.',
    allergies: 'None known',
    medications: 'Acetaminophen 500mg PRN',
    is_active: true,
    created_at: '2024-03-15T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
  },
  {
    id: 'pat-3',
    mrn: 'MRN-2024-003',
    full_name: 'Maria Garcia',
    date_of_birth: '1992-11-08',
    gender: 'female',
    phone: '+1 (555) 456-7890',
    email: 'maria.garcia@email.com',
    address: '789 Pine Road',
    city: 'Springfield',
    state: 'IL',
    zip: '62703',
    referring_physician: 'Dr. Sandra Lee',
    primary_diagnosis: 'Stroke Rehabilitation (CVA)',
    medical_history: 'Ischemic stroke January 2024. Mild left-sided weakness.',
    allergies: 'Aspirin',
    medications: 'Clopidogrel 75mg daily, Lisinopril 10mg daily',
    is_active: true,
    created_at: '2024-02-01T11:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
  },
  {
    id: 'pat-4',
    mrn: 'MRN-2024-004',
    full_name: 'David Wilson',
    date_of_birth: '1965-05-30',
    gender: 'male',
    phone: '+1 (555) 567-8901',
    email: 'david.wilson@email.com',
    address: '321 Elm Street',
    city: 'Springfield',
    state: 'IL',
    zip: '62704',
    emergency_contact_name: 'Susan Wilson',
    emergency_contact_phone: '+1 (555) 567-8902',
    insurance_provider: 'Medicare',
    insurance_policy_number: 'MED-654321987',
    primary_diagnosis: 'Knee Osteoarthritis',
    medical_history: 'Bilateral knee OA. Diabetes Type 2. Hypertension.',
    allergies: 'Sulfa drugs',
    medications: 'Metformin 1000mg twice daily, Amlodipine 5mg daily',
    is_active: true,
    created_at: '2024-01-20T14:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
  },
  {
    id: 'pat-5',
    mrn: 'MRN-2024-005',
    full_name: 'Sarah Thompson',
    date_of_birth: '2000-09-14',
    gender: 'female',
    phone: '+1 (555) 678-9012',
    email: 'sarah.t@email.com',
    address: '654 Birch Lane',
    city: 'Springfield',
    state: 'IL',
    zip: '62705',
    referring_physician: 'Dr. Mark Edwards',
    primary_diagnosis: 'ACL Reconstruction Rehab',
    medical_history: 'Right ACL reconstruction February 2024. Sports injury (basketball).',
    allergies: 'None',
    medications: 'None',
    is_active: true,
    created_at: '2024-02-20T09:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
  },
  {
    id: 'pat-6',
    mrn: 'MRN-2024-006',
    full_name: 'Robert Brown',
    date_of_birth: '1955-12-03',
    gender: 'male',
    phone: '+1 (555) 789-0123',
    email: 'rbrown@email.com',
    address: '987 Cedar Drive',
    city: 'Springfield',
    state: 'IL',
    zip: '62706',
    emergency_contact_name: 'Janet Brown',
    emergency_contact_phone: '+1 (555) 789-0124',
    insurance_provider: 'UnitedHealth',
    insurance_policy_number: 'UHC-321654987',
    primary_diagnosis: "Parkinson's Disease - Balance & Gait",
    medical_history: "Parkinson's Disease diagnosed 2018. History of falls.",
    allergies: 'None known',
    medications: 'Levodopa 100mg three times daily',
    is_active: true,
    created_at: '2024-03-01T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
  },
]

export const mockAppointments: Appointment[] = [
  {
    id: 'apt-1',
    patient_id: 'pat-1',
    therapist_id: 'staff-1',
    appointment_date: '2026-05-19',
    appointment_time: '09:00',
    duration_minutes: 60,
    type: 'follow_up',
    status: 'scheduled',
    reason: 'Regular physiotherapy session - lower back',
    room: 'Room 1',
    created_at: '2024-05-15T10:00:00Z',
    updated_at: '2024-05-15T10:00:00Z',
    patient: mockPatients[0],
    therapist: mockStaff[0],
  },
  {
    id: 'apt-2',
    patient_id: 'pat-2',
    therapist_id: 'staff-4',
    appointment_date: '2026-05-19',
    appointment_time: '10:30',
    duration_minutes: 45,
    type: 'physiotherapy',
    status: 'scheduled',
    reason: 'Post-op shoulder rehab - week 8',
    room: 'Gym',
    created_at: '2024-05-15T10:00:00Z',
    updated_at: '2024-05-15T10:00:00Z',
    patient: mockPatients[1],
    therapist: mockStaff[3],
  },
  {
    id: 'apt-3',
    patient_id: 'pat-3',
    therapist_id: 'staff-2',
    appointment_date: '2026-05-19',
    appointment_time: '11:00',
    duration_minutes: 60,
    type: 'occupational_therapy',
    status: 'completed',
    reason: 'Stroke rehab - ADL training',
    room: 'Room 2',
    created_at: '2024-05-15T10:00:00Z',
    updated_at: '2024-05-15T10:00:00Z',
    patient: mockPatients[2],
    therapist: mockStaff[1],
  },
  {
    id: 'apt-4',
    patient_id: 'pat-4',
    therapist_id: 'staff-1',
    appointment_date: '2026-05-19',
    appointment_time: '14:00',
    duration_minutes: 60,
    type: 'physiotherapy',
    status: 'scheduled',
    reason: 'Knee strengthening exercises',
    room: 'Room 1',
    created_at: '2024-05-15T10:00:00Z',
    updated_at: '2024-05-15T10:00:00Z',
    patient: mockPatients[3],
    therapist: mockStaff[0],
  },
  {
    id: 'apt-5',
    patient_id: 'pat-5',
    therapist_id: 'staff-4',
    appointment_date: '2026-05-20',
    appointment_time: '09:30',
    duration_minutes: 60,
    type: 'physiotherapy',
    status: 'scheduled',
    reason: 'ACL rehab - Phase 3 strengthening',
    room: 'Gym',
    created_at: '2024-05-16T10:00:00Z',
    updated_at: '2024-05-16T10:00:00Z',
    patient: mockPatients[4],
    therapist: mockStaff[3],
  },
  {
    id: 'apt-6',
    patient_id: 'pat-6',
    therapist_id: 'staff-1',
    appointment_date: '2026-05-18',
    appointment_time: '10:00',
    duration_minutes: 60,
    type: 'physiotherapy',
    status: 'completed',
    reason: 'Balance training and gait analysis',
    room: 'Room 3',
    created_at: '2024-05-10T10:00:00Z',
    updated_at: '2024-05-18T11:00:00Z',
    patient: mockPatients[5],
    therapist: mockStaff[0],
  },
  {
    id: 'apt-7',
    patient_id: 'pat-1',
    therapist_id: 'staff-3',
    appointment_date: '2026-05-17',
    appointment_time: '15:00',
    duration_minutes: 45,
    type: 'follow_up',
    status: 'no-show',
    reason: 'Lumbar spine follow-up',
    room: 'Room 1',
    created_at: '2024-05-10T10:00:00Z',
    updated_at: '2024-05-17T16:00:00Z',
    patient: mockPatients[0],
    therapist: mockStaff[2],
  },
]

export const mockSOAPNotes: SOAPNote[] = [
  {
    id: 'note-0a',
    patient_id: 'pat-1',
    therapist_id: 'staff-1',
    session_date: '2026-04-28',
    subjective: 'Initial assessment. Patient reports severe lower back pain radiating to left hip, onset 3 weeks ago after lifting. Pain scale 8/10. Unable to sit longer than 10 minutes.',
    objective: 'ROM: Lumbar flexion 30°, extension 10°. Positive slump test on left. Significant paraspinal guarding L3-L5. Antalgic gait.',
    assessment: 'Acute lumbar strain with associated muscle guarding. No red flags. Good candidate for conservative physiotherapy management.',
    plan: '1. Begin gentle McKenzie extension protocol. 2. Heat therapy pre-session. 3. Education on posture and lifting mechanics. 4. Review in 1 week.',
    pain_scale: 8,
    functional_goals: 'Reduce pain to allow 30 minutes of sitting; restore independent daily activities.',
    next_session_plan: 'Reassess ROM; progress extension exercises if tolerated.',
    created_at: '2026-04-28T09:15:00Z',
    updated_at: '2026-04-28T09:15:00Z',
    patient: mockPatients[0],
    therapist: mockStaff[0],
  },
  {
    id: 'note-0b',
    patient_id: 'pat-1',
    therapist_id: 'staff-1',
    session_date: '2026-05-05',
    subjective: 'Patient reports moderate improvement. Pain scale 6/10. Sitting tolerance up to 25 minutes. Sleep less disturbed.',
    objective: 'ROM: Lumbar flexion 45°, extension 15°. Slump test now negative. Reduced paraspinal guarding (3/5 severity). Gait improving.',
    assessment: 'Responding well to extension-based protocol. Muscle guarding reducing. On track with expected recovery timeline.',
    plan: '1. Progress McKenzie exercises. 2. Introduce gentle core activation. 3. Continue posture education. 4. Review in 1 week.',
    pain_scale: 6,
    functional_goals: 'Return to full-time desk work without pain; participate in recreational walking 5km.',
    next_session_plan: 'Add core stabilization if pain continues to decrease.',
    created_at: '2026-05-05T09:45:00Z',
    updated_at: '2026-05-05T09:45:00Z',
    patient: mockPatients[0],
    therapist: mockStaff[0],
  },
  {
    id: 'note-1',
    patient_id: 'pat-1',
    appointment_id: 'apt-1',
    therapist_id: 'staff-1',
    session_date: '2026-05-12',
    subjective: 'Patient reports improvement in lower back pain. Pain scale 4/10 (down from 7/10 last week). Able to walk 20 minutes without significant discomfort. Reports difficulty with prolonged sitting at work.',
    objective: 'ROM: Lumbar flexion 60° (improved from 45°), extension 20°, lateral flexion R 25° / L 22°. Straight leg raise negative bilaterally. Tenderness at L4-L5 paraspinal muscles (2/5 severity). Gait pattern normal.',
    assessment: 'Patient demonstrates continued improvement in lumbar mobility and pain reduction. Paraspinal muscle tension remains but is improving with current treatment protocol. Functional limitations with sitting posture persist.',
    plan: '1. Continue McKenzie exercises 2x daily. 2. Add core stabilization exercises (plank progression). 3. Ergonomic assessment for workstation. 4. Follow up in 1 week. 5. Consider discharge planning in 4-6 weeks if progress continues.',
    pain_scale: 4,
    functional_goals: 'Return to full-time desk work without pain; participate in recreational walking 5km.',
    next_session_plan: 'Progress to advanced core stabilization. Introduce neural mobilization techniques.',
    created_at: '2026-05-12T10:30:00Z',
    updated_at: '2026-05-12T10:30:00Z',
    patient: mockPatients[0],
    therapist: mockStaff[0],
  },
  {
    id: 'note-2',
    patient_id: 'pat-2',
    appointment_id: 'apt-2',
    therapist_id: 'staff-4',
    session_date: '2026-05-15',
    subjective: 'Patient reports shoulder pain improved to 3/10. Can now lift arm to shoulder height. Sleeping on affected side still uncomfortable. Motivated and compliant with home exercise program.',
    objective: 'Shoulder ROM: Flexion 130° (target 180°), Abduction 120°, IR 45°, ER 55°. MMT: Supraspinatus 4/5, Infraspinatus 4/5. Hawkins-Kennedy test negative. Drop arm test negative.',
    assessment: 'Week 8 post-op rotator cuff repair showing good progress. Strength approaching functional levels. ROM still limited but improving consistently.',
    plan: '1. Progress shoulder press from 2kg to 3kg. 2. Add proprioception exercises. 3. Begin sport-specific activities assessment. 4. Continue home exercise program. 5. Review in 1 week.',
    pain_scale: 3,
    functional_goals: 'Full shoulder ROM; return to swimming; lift 10kg overhead.',
    next_session_plan: 'Introduce resistance band rotator cuff exercises at higher resistance.',
    created_at: '2026-05-15T11:00:00Z',
    updated_at: '2026-05-15T11:00:00Z',
    patient: mockPatients[1],
    therapist: mockStaff[3],
  },
  {
    id: 'note-3',
    patient_id: 'pat-3',
    appointment_id: 'apt-3',
    therapist_id: 'staff-2',
    session_date: '2026-05-19',
    subjective: 'Patient reports feeling more confident with transfers. Family reports she is attempting to dress herself in the morning. Still requires assistance with buttons and clasps. Mood appears improved.',
    objective: 'Berg Balance Scale: 42/56 (improved from 35). Grip strength L: 18kg, R: 31kg. Independent with bed-to-chair transfer. Requires minimal assistance with sit-to-stand. Upper extremity coordination improving.',
    assessment: 'Continued progress in ADL independence and balance following CVA. Upper extremity coordination improving but fine motor tasks remain challenging.',
    plan: '1. Continue ADL training with focus on fine motor tasks. 2. Introduce adaptive equipment for dressing. 3. Caregiver education on optimal assistance levels. 4. Refer to speech therapy for swallowing re-evaluation. 5. Follow up 2x/week.',
    pain_scale: 2,
    functional_goals: 'Independent with all self-care ADLs; safe community ambulation with cane.',
    next_session_plan: 'Focus on upper extremity fine motor training using pegboard and coin tasks.',
    created_at: '2026-05-19T11:45:00Z',
    updated_at: '2026-05-19T11:45:00Z',
    patient: mockPatients[2],
    therapist: mockStaff[1],
  },
]

const mockInvoiceItems1: InvoiceItem[] = [
  { id: 'item-1-1', invoice_id: 'inv-1', description: 'Initial Assessment (60 min)', quantity: 1, unit_price: 250, total: 250 },
  { id: 'item-1-2', invoice_id: 'inv-1', description: 'Physiotherapy Session (60 min)', quantity: 3, unit_price: 150, total: 450 },
  { id: 'item-1-3', invoice_id: 'inv-1', description: 'Exercise Therapy Materials', quantity: 1, unit_price: 35, total: 35 },
]

const mockInvoiceItems2: InvoiceItem[] = [
  { id: 'item-2-1', invoice_id: 'inv-2', description: 'Post-Op Physiotherapy (60 min)', quantity: 4, unit_price: 160, total: 640 },
  { id: 'item-2-2', invoice_id: 'inv-2', description: 'Hydrotherapy Session (45 min)', quantity: 2, unit_price: 120, total: 240 },
]

const mockInvoiceItems3: InvoiceItem[] = [
  { id: 'item-3-1', invoice_id: 'inv-3', description: 'Occupational Therapy Session (60 min)', quantity: 6, unit_price: 155, total: 930 },
  { id: 'item-3-2', invoice_id: 'inv-3', description: 'Adaptive Equipment Provision', quantity: 1, unit_price: 85, total: 85 },
]

const mockInvoiceItems4: InvoiceItem[] = [
  { id: 'item-4-1', invoice_id: 'inv-4', description: 'Physiotherapy Session (60 min)', quantity: 5, unit_price: 150, total: 750 },
]

export const mockInvoices: Invoice[] = [
  {
    id: 'inv-1',
    invoice_number: 'INV-2024-001',
    patient_id: 'pat-1',
    appointment_id: 'apt-1',
    status: 'paid',
    issue_date: '2026-04-30',
    due_date: '2026-05-15',
    paid_date: '2026-05-10',
    subtotal: 735,
    tax_rate: 0,
    tax_amount: 0,
    discount_amount: 0,
    total_amount: 735,
    items: mockInvoiceItems1,
    notes: 'Insurance claim submitted. Patient co-pay collected.',
    created_at: '2026-04-30T10:00:00Z',
    updated_at: '2026-05-10T10:00:00Z',
    patient: mockPatients[0],
  },
  {
    id: 'inv-2',
    invoice_number: 'INV-2024-002',
    patient_id: 'pat-2',
    status: 'sent',
    issue_date: '2026-05-01',
    due_date: '2026-05-31',
    subtotal: 880,
    tax_rate: 0,
    tax_amount: 0,
    discount_amount: 50,
    total_amount: 830,
    items: mockInvoiceItems2,
    notes: 'Loyalty discount applied.',
    created_at: '2026-05-01T10:00:00Z',
    updated_at: '2026-05-01T10:00:00Z',
    patient: mockPatients[1],
  },
  {
    id: 'inv-3',
    invoice_number: 'INV-2024-003',
    patient_id: 'pat-3',
    status: 'overdue',
    issue_date: '2026-04-15',
    due_date: '2026-05-01',
    subtotal: 1015,
    tax_rate: 0,
    tax_amount: 0,
    discount_amount: 0,
    total_amount: 1015,
    items: mockInvoiceItems3,
    created_at: '2026-04-15T10:00:00Z',
    updated_at: '2026-04-15T10:00:00Z',
    patient: mockPatients[2],
  },
  {
    id: 'inv-4',
    invoice_number: 'INV-2024-004',
    patient_id: 'pat-4',
    status: 'draft',
    issue_date: '2026-05-19',
    due_date: '2026-06-18',
    subtotal: 750,
    tax_rate: 0,
    tax_amount: 0,
    discount_amount: 0,
    total_amount: 750,
    items: mockInvoiceItems4,
    created_at: '2026-05-19T09:00:00Z',
    updated_at: '2026-05-19T09:00:00Z',
    patient: mockPatients[3],
  },
  {
    id: 'inv-5',
    invoice_number: 'INV-2024-005',
    patient_id: 'pat-5',
    status: 'paid',
    issue_date: '2026-04-20',
    due_date: '2026-05-05',
    paid_date: '2026-04-28',
    subtotal: 600,
    tax_rate: 0,
    tax_amount: 0,
    discount_amount: 0,
    total_amount: 600,
    items: [{ id: 'item-5-1', invoice_id: 'inv-5', description: 'Physiotherapy Session (60 min)', quantity: 4, unit_price: 150, total: 600 }],
    created_at: '2026-04-20T10:00:00Z',
    updated_at: '2026-04-28T10:00:00Z',
    patient: mockPatients[4],
  },
]

export const mockRecentActivity: RecentActivity[] = [
  {
    id: 'act-1',
    type: 'appointment',
    description: 'Appointment completed for Emily Johnson',
    timestamp: '2026-05-19T11:30:00Z',
    user_name: 'Dr. Swechchha Rajput',
  },
  {
    id: 'act-2',
    type: 'note',
    description: 'SOAP note added for Maria Garcia',
    timestamp: '2026-05-19T11:45:00Z',
    user_name: 'Dr. James Okafor',
  },
  {
    id: 'act-3',
    type: 'invoice',
    description: 'Invoice INV-2024-001 marked as paid',
    timestamp: '2026-05-18T14:20:00Z',
    user_name: 'Dr. Swechchha Rajput',
  },
  {
    id: 'act-4',
    type: 'patient',
    description: 'New patient Robert Brown registered',
    timestamp: '2026-05-18T09:15:00Z',
    user_name: 'Dr. Swechchha Rajput',
  },
  {
    id: 'act-5',
    type: 'appointment',
    description: 'Appointment scheduled for Sarah Thompson',
    timestamp: '2026-05-17T16:00:00Z',
    user_name: 'Mr. Carlos Rivera',
  },
]
